// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0 (
        ap_ready,
        data_V_read,
        ap_return
);


output   ap_ready;
input  [31:0] data_V_read;
output  [15:0] ap_return;

wire  signed [15:0] mul_ln1118_fu_54_p1;
wire   [15:0] trunc_ln1118_fu_72_p1;
wire   [24:0] shl_ln_fu_76_p3;
wire   [17:0] shl_ln1118_1_fu_88_p3;
wire  signed [25:0] sext_ln1118_1_fu_96_p1;
wire  signed [25:0] sext_ln1118_fu_84_p1;
wire   [25:0] sub_ln1118_fu_100_p2;
wire   [15:0] tmp_1_fu_116_p4;
wire   [25:0] mul_ln1118_fu_54_p2;
wire   [15:0] trunc_ln708_1_fu_131_p4;
wire   [15:0] add_ln703_fu_141_p2;
wire   [15:0] trunc_ln_fu_106_p4;

assign add_ln703_fu_141_p2 = ($signed(16'd65255) + $signed(trunc_ln708_1_fu_131_p4));

assign ap_ready = 1'b1;

assign ap_return = (add_ln703_fu_141_p2 + trunc_ln_fu_106_p4);

assign mul_ln1118_fu_54_p1 = tmp_1_fu_116_p4;

assign mul_ln1118_fu_54_p2 = ($signed(26'd67108108) * $signed(mul_ln1118_fu_54_p1));

assign sext_ln1118_1_fu_96_p1 = $signed(shl_ln1118_1_fu_88_p3);

assign sext_ln1118_fu_84_p1 = $signed(shl_ln_fu_76_p3);

assign shl_ln1118_1_fu_88_p3 = {{trunc_ln1118_fu_72_p1}, {2'd0}};

assign shl_ln_fu_76_p3 = {{trunc_ln1118_fu_72_p1}, {9'd0}};

assign sub_ln1118_fu_100_p2 = ($signed(sext_ln1118_1_fu_96_p1) - $signed(sext_ln1118_fu_84_p1));

assign tmp_1_fu_116_p4 = {{data_V_read[31:16]}};

assign trunc_ln1118_fu_72_p1 = data_V_read[15:0];

assign trunc_ln708_1_fu_131_p4 = {{mul_ln1118_fu_54_p2[25:10]}};

assign trunc_ln_fu_106_p4 = {{sub_ln1118_fu_100_p2[25:10]}};

endmodule //dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0
