// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::ap_const_logic_1 = sc_dt::Log_1;
const bool dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::ap_const_boolean_1 = true;
const sc_lv<26> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::ap_const_lv26_3FFFD0C = "11111111111111110100001100";
const sc_lv<9> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::ap_const_lv9_0 = "000000000";
const sc_lv<2> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::ap_const_lv2_0 = "00";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::ap_const_lv32_A = "1010";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::ap_const_lv32_19 = "11001";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::ap_const_lv32_10 = "10000";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::ap_const_lv32_1F = "11111";
const sc_lv<16> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::ap_const_lv16_FEE7 = "1111111011100111";
const sc_logic dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::ap_const_logic_0 = sc_dt::Log_0;

dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_add_ln703_fu_141_p2);
    sensitive << ( trunc_ln708_1_fu_131_p4 );

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return);
    sensitive << ( add_ln703_fu_141_p2 );
    sensitive << ( trunc_ln_fu_106_p4 );

    SC_METHOD(thread_mul_ln1118_fu_54_p1);
    sensitive << ( tmp_1_fu_116_p4 );

    SC_METHOD(thread_mul_ln1118_fu_54_p2);
    sensitive << ( mul_ln1118_fu_54_p1 );

    SC_METHOD(thread_sext_ln1118_1_fu_96_p1);
    sensitive << ( shl_ln1118_1_fu_88_p3 );

    SC_METHOD(thread_sext_ln1118_fu_84_p1);
    sensitive << ( shl_ln_fu_76_p3 );

    SC_METHOD(thread_shl_ln1118_1_fu_88_p3);
    sensitive << ( trunc_ln1118_fu_72_p1 );

    SC_METHOD(thread_shl_ln_fu_76_p3);
    sensitive << ( trunc_ln1118_fu_72_p1 );

    SC_METHOD(thread_sub_ln1118_fu_100_p2);
    sensitive << ( sext_ln1118_1_fu_96_p1 );
    sensitive << ( sext_ln1118_fu_84_p1 );

    SC_METHOD(thread_tmp_1_fu_116_p4);
    sensitive << ( data_V_read );

    SC_METHOD(thread_trunc_ln1118_fu_72_p1);
    sensitive << ( data_V_read );

    SC_METHOD(thread_trunc_ln708_1_fu_131_p4);
    sensitive << ( mul_ln1118_fu_54_p2 );

    SC_METHOD(thread_trunc_ln_fu_106_p4);
    sensitive << ( sub_ln1118_fu_100_p2 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_V_read, "(port)data_V_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, mul_ln1118_fu_54_p1, "mul_ln1118_fu_54_p1");
    sc_trace(mVcdFile, trunc_ln1118_fu_72_p1, "trunc_ln1118_fu_72_p1");
    sc_trace(mVcdFile, shl_ln_fu_76_p3, "shl_ln_fu_76_p3");
    sc_trace(mVcdFile, shl_ln1118_1_fu_88_p3, "shl_ln1118_1_fu_88_p3");
    sc_trace(mVcdFile, sext_ln1118_1_fu_96_p1, "sext_ln1118_1_fu_96_p1");
    sc_trace(mVcdFile, sext_ln1118_fu_84_p1, "sext_ln1118_fu_84_p1");
    sc_trace(mVcdFile, sub_ln1118_fu_100_p2, "sub_ln1118_fu_100_p2");
    sc_trace(mVcdFile, tmp_1_fu_116_p4, "tmp_1_fu_116_p4");
    sc_trace(mVcdFile, mul_ln1118_fu_54_p2, "mul_ln1118_fu_54_p2");
    sc_trace(mVcdFile, trunc_ln708_1_fu_131_p4, "trunc_ln708_1_fu_131_p4");
    sc_trace(mVcdFile, add_ln703_fu_141_p2, "add_ln703_fu_141_p2");
    sc_trace(mVcdFile, trunc_ln_fu_106_p4, "trunc_ln_fu_106_p4");
#endif

    }
}

dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::~dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::thread_add_ln703_fu_141_p2() {
    add_ln703_fu_141_p2 = (!ap_const_lv16_FEE7.is_01() || !trunc_ln708_1_fu_131_p4.read().is_01())? sc_lv<16>(): (sc_bigint<16>(ap_const_lv16_FEE7) + sc_biguint<16>(trunc_ln708_1_fu_131_p4.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::thread_ap_return() {
    ap_return = (!add_ln703_fu_141_p2.read().is_01() || !trunc_ln_fu_106_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_fu_141_p2.read()) + sc_biguint<16>(trunc_ln_fu_106_p4.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::thread_mul_ln1118_fu_54_p1() {
    mul_ln1118_fu_54_p1 = tmp_1_fu_116_p4.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::thread_mul_ln1118_fu_54_p2() {
    mul_ln1118_fu_54_p2 = (!ap_const_lv26_3FFFD0C.is_01() || !mul_ln1118_fu_54_p1.read().is_01())? sc_lv<26>(): sc_bigint<26>(ap_const_lv26_3FFFD0C) * sc_bigint<16>(mul_ln1118_fu_54_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::thread_sext_ln1118_1_fu_96_p1() {
    sext_ln1118_1_fu_96_p1 = esl_sext<26,18>(shl_ln1118_1_fu_88_p3.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::thread_sext_ln1118_fu_84_p1() {
    sext_ln1118_fu_84_p1 = esl_sext<26,25>(shl_ln_fu_76_p3.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::thread_shl_ln1118_1_fu_88_p3() {
    shl_ln1118_1_fu_88_p3 = esl_concat<16,2>(trunc_ln1118_fu_72_p1.read(), ap_const_lv2_0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::thread_shl_ln_fu_76_p3() {
    shl_ln_fu_76_p3 = esl_concat<16,9>(trunc_ln1118_fu_72_p1.read(), ap_const_lv9_0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::thread_sub_ln1118_fu_100_p2() {
    sub_ln1118_fu_100_p2 = (!sext_ln1118_1_fu_96_p1.read().is_01() || !sext_ln1118_fu_84_p1.read().is_01())? sc_lv<26>(): (sc_bigint<26>(sext_ln1118_1_fu_96_p1.read()) - sc_bigint<26>(sext_ln1118_fu_84_p1.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::thread_tmp_1_fu_116_p4() {
    tmp_1_fu_116_p4 = data_V_read.read().range(31, 16);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::thread_trunc_ln1118_fu_72_p1() {
    trunc_ln1118_fu_72_p1 = data_V_read.read().range(16-1, 0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::thread_trunc_ln708_1_fu_131_p4() {
    trunc_ln708_1_fu_131_p4 = mul_ln1118_fu_54_p2.read().range(25, 10);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0::thread_trunc_ln_fu_106_p4() {
    trunc_ln_fu_106_p4 = sub_ln1118_fu_100_p2.read().range(25, 10);
}

}

