// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0_HH_
#define _dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0 : public sc_module {
    // Port declarations 3
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > data_V_read;
    sc_out< sc_lv<16> > ap_return;


    // Module declarations
    dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0(sc_module_name name);
    SC_HAS_PROCESS(dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0);

    ~dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<16> > mul_ln1118_fu_54_p1;
    sc_signal< sc_lv<16> > trunc_ln1118_fu_72_p1;
    sc_signal< sc_lv<25> > shl_ln_fu_76_p3;
    sc_signal< sc_lv<18> > shl_ln1118_1_fu_88_p3;
    sc_signal< sc_lv<26> > sext_ln1118_1_fu_96_p1;
    sc_signal< sc_lv<26> > sext_ln1118_fu_84_p1;
    sc_signal< sc_lv<26> > sub_ln1118_fu_100_p2;
    sc_signal< sc_lv<16> > tmp_1_fu_116_p4;
    sc_signal< sc_lv<26> > mul_ln1118_fu_54_p2;
    sc_signal< sc_lv<16> > trunc_ln708_1_fu_131_p4;
    sc_signal< sc_lv<16> > add_ln703_fu_141_p2;
    sc_signal< sc_lv<16> > trunc_ln_fu_106_p4;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<26> ap_const_lv26_3FFFD0C;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<16> ap_const_lv16_FEE7;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_add_ln703_fu_141_p2();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_mul_ln1118_fu_54_p1();
    void thread_mul_ln1118_fu_54_p2();
    void thread_sext_ln1118_1_fu_96_p1();
    void thread_sext_ln1118_fu_84_p1();
    void thread_shl_ln1118_1_fu_88_p3();
    void thread_shl_ln_fu_76_p3();
    void thread_sub_ln1118_fu_100_p2();
    void thread_tmp_1_fu_116_p4();
    void thread_trunc_ln1118_fu_72_p1();
    void thread_trunc_ln708_1_fu_131_p4();
    void thread_trunc_ln_fu_106_p4();
};

}

using namespace ap_rtl;

#endif
