// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _nn_top_HH_
#define _nn_top_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "myproject.h"

namespace ap_rtl {

struct nn_top : public sc_module {
    // Port declarations 5
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<16> > x0_V;
    sc_in< sc_lv<16> > x1_V;
    sc_out< sc_lv<16> > y_V;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    nn_top(sc_module_name name);
    SC_HAS_PROCESS(nn_top);

    ~nn_top();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    myproject* call_ret_myproject_fu_55;
    sc_signal< sc_logic > call_ret_myproject_fu_55_ap_start;
    sc_signal< sc_logic > call_ret_myproject_fu_55_ap_done;
    sc_signal< sc_logic > call_ret_myproject_fu_55_ap_idle;
    sc_signal< sc_logic > call_ret_myproject_fu_55_ap_ready;
    sc_signal< sc_lv<15> > call_ret_myproject_fu_55_ap_return;
    sc_signal< sc_logic > call_ret_myproject_fu_55_dense_input_V_blk_n;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > in_V_fu_32;
    sc_signal< sc_lv<32> > in_V_1_fu_60_p3;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_call_ret_myproject_fu_55_ap_start();
    void thread_in_V_1_fu_60_p3();
    void thread_y_V();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
