// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "nn_top.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic nn_top::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic nn_top::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> nn_top::ap_ST_fsm_state1 = "1";
const sc_lv<2> nn_top::ap_ST_fsm_state2 = "10";
const sc_lv<32> nn_top::ap_const_lv32_1 = "1";
const sc_lv<32> nn_top::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool nn_top::ap_const_boolean_1 = true;

nn_top::nn_top(sc_module_name name) : sc_module(name), mVcdFile(0) {
    call_ret_myproject_fu_55 = new myproject("call_ret_myproject_fu_55");
    call_ret_myproject_fu_55->ap_clk(ap_clk);
    call_ret_myproject_fu_55->ap_rst(ap_rst);
    call_ret_myproject_fu_55->ap_start(call_ret_myproject_fu_55_ap_start);
    call_ret_myproject_fu_55->ap_done(call_ret_myproject_fu_55_ap_done);
    call_ret_myproject_fu_55->ap_idle(call_ret_myproject_fu_55_ap_idle);
    call_ret_myproject_fu_55->ap_ready(call_ret_myproject_fu_55_ap_ready);
    call_ret_myproject_fu_55->dense_input_V(in_V_fu_32);
    call_ret_myproject_fu_55->dense_input_V_ap_vld(ap_var_for_const0);
    call_ret_myproject_fu_55->ap_return(call_ret_myproject_fu_55_ap_return);
    call_ret_myproject_fu_55->dense_input_V_blk_n(call_ret_myproject_fu_55_dense_input_V_blk_n);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_call_ret_myproject_fu_55_ap_start);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_in_V_1_fu_60_p3);
    sensitive << ( x0_V );
    sensitive << ( x1_V );

    SC_METHOD(thread_y_V);
    sensitive << ( call_ret_myproject_fu_55_ap_return );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "nn_top_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, x0_V, "(port)x0_V");
    sc_trace(mVcdFile, x1_V, "(port)x1_V");
    sc_trace(mVcdFile, y_V, "(port)y_V");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, call_ret_myproject_fu_55_ap_start, "call_ret_myproject_fu_55_ap_start");
    sc_trace(mVcdFile, call_ret_myproject_fu_55_ap_done, "call_ret_myproject_fu_55_ap_done");
    sc_trace(mVcdFile, call_ret_myproject_fu_55_ap_idle, "call_ret_myproject_fu_55_ap_idle");
    sc_trace(mVcdFile, call_ret_myproject_fu_55_ap_ready, "call_ret_myproject_fu_55_ap_ready");
    sc_trace(mVcdFile, call_ret_myproject_fu_55_ap_return, "call_ret_myproject_fu_55_ap_return");
    sc_trace(mVcdFile, call_ret_myproject_fu_55_dense_input_V_blk_n, "call_ret_myproject_fu_55_dense_input_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, in_V_fu_32, "in_V_fu_32");
    sc_trace(mVcdFile, in_V_1_fu_60_p3, "in_V_1_fu_60_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("nn_top.hdltvin.dat");
    mHdltvoutHandle.open("nn_top.hdltvout.dat");
}

nn_top::~nn_top() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete call_ret_myproject_fu_55;
}

void nn_top::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void nn_top::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        in_V_fu_32 = in_V_1_fu_60_p3.read();
    }
}

void nn_top::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void nn_top::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void nn_top::thread_call_ret_myproject_fu_55_ap_start() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        call_ret_myproject_fu_55_ap_start = ap_const_logic_1;
    } else {
        call_ret_myproject_fu_55_ap_start = ap_const_logic_0;
    }
}

void nn_top::thread_in_V_1_fu_60_p3() {
    in_V_1_fu_60_p3 = esl_concat<16,16>(x1_V.read(), x0_V.read());
}

void nn_top::thread_y_V() {
    y_V = esl_zext<16,15>(call_ret_myproject_fu_55_ap_return.read());
}

void nn_top::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

void nn_top::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"x0_V\" :  \"" << x0_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"x1_V\" :  \"" << x1_V.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"y_V\" :  \"" << y_V.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

