// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s::ap_const_logic_1 = sc_dt::Log_1;
const bool relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s::ap_const_boolean_1 = true;
const sc_lv<16> relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s::ap_const_lv16_0 = "0000000000000000";
const sc_lv<15> relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s::ap_const_lv15_0 = "000000000000000";
const sc_logic relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s::ap_const_logic_0 = sc_dt::Log_0;

relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s::relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return);
    sensitive << ( icmp_ln1494_fu_24_p2 );
    sensitive << ( trunc_ln45_fu_30_p1 );

    SC_METHOD(thread_icmp_ln1494_fu_24_p2);
    sensitive << ( data_V_read );

    SC_METHOD(thread_trunc_ln45_fu_30_p1);
    sensitive << ( data_V_read );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_V_read, "(port)data_V_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, icmp_ln1494_fu_24_p2, "icmp_ln1494_fu_24_p2");
    sc_trace(mVcdFile, trunc_ln45_fu_30_p1, "trunc_ln45_fu_30_p1");
#endif

    }
}

relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s::~relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s::thread_ap_return() {
    ap_return = (!icmp_ln1494_fu_24_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_fu_24_p2.read()[0].to_bool())? trunc_ln45_fu_30_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s::thread_icmp_ln1494_fu_24_p2() {
    icmp_ln1494_fu_24_p2 = (!data_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s::thread_trunc_ln45_fu_30_p1() {
    trunc_ln45_fu_30_p1 = data_V_read.read().range(15-1, 0);
}

}

