-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0 is
port (
    ap_ready : OUT STD_LOGIC;
    data_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_0_0 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv26_3FFFD0C : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110100001100";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv16_FEE7 : STD_LOGIC_VECTOR (15 downto 0) := "1111111011100111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal mul_ln1118_fu_54_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1118_fu_72_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_fu_76_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal shl_ln1118_1_fu_88_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1118_1_fu_96_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1118_fu_84_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sub_ln1118_fu_100_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_1_fu_116_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_fu_54_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln708_1_fu_131_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_fu_141_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_fu_106_p4 : STD_LOGIC_VECTOR (15 downto 0);


begin



    add_ln703_fu_141_p2 <= std_logic_vector(signed(ap_const_lv16_FEE7) + signed(trunc_ln708_1_fu_131_p4));
    ap_ready <= ap_const_logic_1;
    ap_return <= std_logic_vector(unsigned(add_ln703_fu_141_p2) + unsigned(trunc_ln_fu_106_p4));
    mul_ln1118_fu_54_p1 <= tmp_1_fu_116_p4;
    mul_ln1118_fu_54_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(ap_const_lv26_3FFFD0C) * signed(mul_ln1118_fu_54_p1))), 26));
        sext_ln1118_1_fu_96_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1118_1_fu_88_p3),26));

        sext_ln1118_fu_84_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_76_p3),26));

    shl_ln1118_1_fu_88_p3 <= (trunc_ln1118_fu_72_p1 & ap_const_lv2_0);
    shl_ln_fu_76_p3 <= (trunc_ln1118_fu_72_p1 & ap_const_lv9_0);
    sub_ln1118_fu_100_p2 <= std_logic_vector(signed(sext_ln1118_1_fu_96_p1) - signed(sext_ln1118_fu_84_p1));
    tmp_1_fu_116_p4 <= data_V_read(31 downto 16);
    trunc_ln1118_fu_72_p1 <= data_V_read(16 - 1 downto 0);
    trunc_ln708_1_fu_131_p4 <= mul_ln1118_fu_54_p2(25 downto 10);
    trunc_ln_fu_106_p4 <= sub_ln1118_fu_100_p2(25 downto 10);
end behav;
