-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nn_top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x0_V : IN STD_LOGIC_VECTOR (15 downto 0);
    x1_V : IN STD_LOGIC_VECTOR (15 downto 0);
    y_V : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of nn_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "nn_top,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu13p-flga2577-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.583500,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=1,HLS_SYN_FF=35,HLS_SYN_LUT=117,HLS_VERSION=2019_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal call_ret_myproject_fu_55_ap_start : STD_LOGIC;
    signal call_ret_myproject_fu_55_ap_done : STD_LOGIC;
    signal call_ret_myproject_fu_55_ap_idle : STD_LOGIC;
    signal call_ret_myproject_fu_55_ap_ready : STD_LOGIC;
    signal call_ret_myproject_fu_55_ap_return : STD_LOGIC_VECTOR (14 downto 0);
    signal call_ret_myproject_fu_55_dense_input_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal in_V_fu_32 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_V_1_fu_60_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);

    component myproject IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        dense_input_V : IN STD_LOGIC_VECTOR (31 downto 0);
        dense_input_V_ap_vld : IN STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (14 downto 0);
        dense_input_V_blk_n : OUT STD_LOGIC );
    end component;



begin
    call_ret_myproject_fu_55 : component myproject
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => call_ret_myproject_fu_55_ap_start,
        ap_done => call_ret_myproject_fu_55_ap_done,
        ap_idle => call_ret_myproject_fu_55_ap_idle,
        ap_ready => call_ret_myproject_fu_55_ap_ready,
        dense_input_V => in_V_fu_32,
        dense_input_V_ap_vld => ap_const_logic_1,
        ap_return => call_ret_myproject_fu_55_ap_return,
        dense_input_V_blk_n => call_ret_myproject_fu_55_dense_input_V_blk_n);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                in_V_fu_32 <= in_V_1_fu_60_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    call_ret_myproject_fu_55_ap_start_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            call_ret_myproject_fu_55_ap_start <= ap_const_logic_1;
        else 
            call_ret_myproject_fu_55_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    in_V_1_fu_60_p3 <= (x1_V & x0_V);
    y_V <= std_logic_vector(IEEE.numeric_std.resize(unsigned(call_ret_myproject_fu_55_ap_return),16));
end behav;
