-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (14 downto 0) );
end;


architecture behav of relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal icmp_ln1494_fu_24_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln45_fu_30_p1 : STD_LOGIC_VECTOR (14 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= 
        trunc_ln45_fu_30_p1 when (icmp_ln1494_fu_24_p2(0) = '1') else 
        ap_const_lv15_0;
    icmp_ln1494_fu_24_p2 <= "1" when (signed(data_V_read) > signed(ap_const_lv16_0)) else "0";
    trunc_ln45_fu_30_p1 <= data_V_read(15 - 1 downto 0);
end behav;
