// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s (
        ap_ready,
        data_V_read,
        ap_return
);


output   ap_ready;
input  [15:0] data_V_read;
output  [14:0] ap_return;

wire   [0:0] icmp_ln1494_fu_24_p2;
wire   [14:0] trunc_ln45_fu_30_p1;

assign ap_ready = 1'b1;

assign ap_return = ((icmp_ln1494_fu_24_p2[0:0] === 1'b1) ? trunc_ln45_fu_30_p1 : 15'd0);

assign icmp_ln1494_fu_24_p2 = (($signed(data_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign trunc_ln45_fu_30_p1 = data_V_read[14:0];

endmodule //relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s