// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="nn_top,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu13p-flga2577-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.583500,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=1,HLS_SYN_FF=35,HLS_SYN_LUT=117,HLS_VERSION=2019_2}" *)

module nn_top (
        ap_clk,
        ap_rst,
        x0_V,
        x1_V,
        y_V
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input  [15:0] x0_V;
input  [15:0] x1_V;
output  [15:0] y_V;

reg    call_ret_myproject_fu_55_ap_start;
wire    call_ret_myproject_fu_55_ap_done;
wire    call_ret_myproject_fu_55_ap_idle;
wire    call_ret_myproject_fu_55_ap_ready;
wire   [14:0] call_ret_myproject_fu_55_ap_return;
wire    call_ret_myproject_fu_55_dense_input_V_blk_n;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;
reg   [31:0] in_V_fu_32;
wire   [31:0] in_V_1_fu_60_p3;
wire    ap_CS_fsm_state1;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

myproject call_ret_myproject_fu_55(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ret_myproject_fu_55_ap_start),
    .ap_done(call_ret_myproject_fu_55_ap_done),
    .ap_idle(call_ret_myproject_fu_55_ap_idle),
    .ap_ready(call_ret_myproject_fu_55_ap_ready),
    .dense_input_V(in_V_fu_32),
    .dense_input_V_ap_vld(1'b1),
    .ap_return(call_ret_myproject_fu_55_ap_return),
    .dense_input_V_blk_n(call_ret_myproject_fu_55_dense_input_V_blk_n)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        in_V_fu_32 <= in_V_1_fu_60_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        call_ret_myproject_fu_55_ap_start = 1'b1;
    end else begin
        call_ret_myproject_fu_55_ap_start = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign in_V_1_fu_60_p3 = {{x1_V}, {x0_V}};

assign y_V = call_ret_myproject_fu_55_ap_return;

endmodule //nn_top
